[build]
  command = "npm run build"
  publish = "build/client"
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  included_files = [
    "node_modules/lucide-react/**",
    "node_modules/framer-motion/**",
    "node_modules/react-icons/**",
    "build/server/**"
  ]
